version: '3'

services:
  mongo:
    image: mongo:5
    ports:
      - 27017:27017
    environment:
      MONGODB_DATABASE: categories
    volumes:
      - ./mongo:/data/mongo
  
  postgres:
    image: postgres:14-alpine
    ports:
      - 5432:5432
    volumes:
      - ./postgres:/data/postgres
    environment:
      - POSTGRES_PASSWORD=admin
      - POSTGRES_USER=admin
      - POSTGRES_DB=products
